version: "3.8"
services:
  nginx-reveal-drei:
    depends_on:
      - presentation-api
      - reveal-drei
      - rabbitmq
      - mongo
      - mongo-express
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4444:4444"

  reveal-drei:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NEXT_PUBLIC_NODE_ENV_DEVELOPMENT=true
      - TEST=hahahahahah
    depends_on:
      - presentation-api
    restart: unless-stopped

  presentation-api:
    build:
      dockerfile: Dockerfile
      context: ./api/presentation
    environment:
      - PORT=4223
      - NODE_ENV=development
      - DB_NAME=presentation
      - ROLE=admin
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - /var/lib/rabbitmq
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - 8002:8081
    depends_on:
      - mongo
    restart: always
