version: "3.8"
services:
  nginx:
    depends_on:
      - socket-api
      - folders-api
      - lessons-api
      - auth-api
      - users-api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3333:3333"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - /var/lib/rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client/app:/app/app
      - ./client/store:/app/store
      - ./client/public:/app/public
      - ./client/components:/app/components
      - ./client/config:/app/config
      - ./client/content:/app/content
      - ./client/hooks:/app/hooks
      - ./client/lib:/app/lib
      - ./client/modules:/app/modules
      - ./client/styles:/app/styles
      - ./client/types:/app/types
      - ./client/containers:/app/containers
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - folders-api
      - lessons-api
      - socket-api
      - auth-api
      - users-api
    restart: unless-stopped

  folders-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/folders
    volumes:
      - ./api/folders/src:/app/src
      - /api/folders/node_modules
    environment:
      - PORT=3010
      - NODE_ENV=development
      - DB_NAME=folders
      - ROLE=admin
      - DB_URI=mongodb://mongo:27017
      - ORIGIN=*
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq

  lessons-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/lessons
    volumes:
      - ./api/lessons/src:/app/src
      - /api/lessons/node_modules
    environment:
      - PORT=3011
      - NODE_ENV=development
      - DB_NAME=lessons
      - ROLE=admin
      - DB_URI=mongodb://mongo:27017
      - ORIGIN=*
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq

  socket-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/socket
    volumes:
      - ./api/socket/src:/app/src
      - /api/socket/node_modules
    environment:
      - PORT=3012
      - NODE_ENV=development
      - DB_NAME=socket
      - ROLE=admin
      - DB_URI=mongodb://mongo:27017
      - ORIGIN=*
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq

  auth-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/auth
    volumes:
      - ./api/auth/src:/app/src
      - /api/auth/node_modules
    environment:
      - PORT=3013
      - NODE_ENV=development
      - DB_NAME=auth
      - ROLE=admin
      - DB_URI=mongodb://mongo:27017
      - SERVICE_NAME=auth
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - ORIGIN=*
      - JWT_SECRET=secret
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq

  users-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/users
    volumes:
      - ./api/users/src:/app/src
      - /api/users/node_modules
    environment:
      - PORT=3014
      - NODE_ENV=development
      - DB_NAME=users
      - SERVICE_NAME=users
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - ROLE=admin
      - DB_URI=mongodb://mongo:27017
      - ORIGIN=*
      - JWT_SECRET=secret
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
